
### Create file
POST http://localhost:7007/api/files
Content-Type: application/json

{
  "folderPath": "Folder2",
  "name": "picture",
  "fileType": ".png"
}

### Read file by id
GET http://localhost:7007/api/files/file/9
Content-Type: application/json

### Update file
PUT http://localhost:7007/api/files
Content-Type: application/json

{
  "id": 1,
  "folderPath": "Folder2",
  "name": "landscape",
  "fileType": ".png"
}

### Delete file
DELETE http://localhost:7007/api/files/2
Content-Type: application/json

### Get all files in path by type
GET http://localhost:7007/api/files/Folder1/.jpg
Content-Type: application/json

### Get all files in path
GET http://localhost:7007/api/files/Folder1
Content-Type: application/json



### Get all log entries
GET http://localhost:7007/api/logs/all
Content-Type: application/json