### Create fileData
POST http://localhost:7007/api/files
Content-Type: application/json

{
  "description": "Upload of file test.",
  "topic": "Test",
  "filePath": "businest\\backend\\src\\main\\resources\\12B.txt"
}

### Read fileData by id
GET http://localhost:7007/api/files/fileData/1
Content-Type: application/json

### Update fileData
PUT http://localhost:7007/api/files
Content-Type: application/json

{
  "id": 1,
  "folderPath": "Folder2",
  "name": "landscape",
  "fileType": ".png",
  "topic": "topic",
  "description": "description"
}

### Delete fileData
DELETE http://localhost:7007/api/files/2
Content-Type: application/json

### Get all files in path by type
GET http://localhost:7007/api/files/Folder1/.jpg
Content-Type: application/json

### Get all files in path
GET http://localhost:7007/api/files/Folder1
Content-Type: application/json

### Get all log entries
GET http://localhost:7007/api/logs/all
Content-Type: application/json