GET http://localhost:7007/api/account
Content-Type: application/json

###

GET http://localhost:7007/api/account/roles_subroles
Content-Type: application/json

###

GET http://localhost:7007/api/account/subroles
Content-Type: application/json

###


GET http://localhost:7007/api/account/1
Content-Type: application/json

###

PUT http://localhost:7007/api/account/update_role
Content-Type: application/json

{
  "id": 1,
  "name": "Alex Johnson updated",
  "role": "Company Manager",
  "subRoles": [
    "Super Manager",
    "HR Specialistddd"
  ]
}


###

POST http://localhost:7007/api/account/
Content-Type: application/json

{
  "id": 11,
  "name": "New USER TEST",
  "role": "Company Manager",
  "subRoles": [
    "Super Manager",
    "HR Specialist"
  ]
}


